name: prgda
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - pip:
    - ipynb==0.5.1
    - numpy==1.20
    - pandas==1.3
    - matplotlib==3.4
    - RISE==5.7.1
    - openpyxl>=3.0
    - xlrd==2.0.1
    - lxml==4.6
    - beautifulsoup4==4.10
    - folium==0.12
